Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Models/Project.cs
namespace ProjectRider.Models
{
    using System.ComponentModel.DataAnnotations;

    public class Project
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public int Budget { get; set; }
    }
}

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Models/ProjectDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace ProjectRider.Models
{
    public class ProjectDbContext : DbContext
    {
        public DbSet<Project> Projects { get; set; }

        public ProjectDbContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySQL("server=localhost;database=projectRiderCSharp;user=root;");
        }
    }
}

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Controllers/ProjectsController.cs
namespace ProjectRider.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using ProjectRider.Models;
    using System.Collections.Generic;
    using System.Linq;

    public class ProjectController : Controller
    {
        private readonly ProjectDbContext context;

        public ProjectController(ProjectDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            List<Project> projects = 
                this.context.Projects
               .ToList();

            return View(projects);
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("create")]
        public ActionResult Create(Project project)
        {
            this.context.Projects.Add(project);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult Edit(int id)
        {
            Project project = this.context.Projects.Find(id);
            return View(project);
        }

        [HttpPost]
        [Route("edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirm(int id, Project projectModel)
        {      
            this.context.Projects.Update(projectModel);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("delete/{id}")]
        public ActionResult Delete(int id)
        {
            Project project = this.context.Projects.Find(id);
            return View(project);
        }

        [HttpPost]
        [Route("delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id, Project projectModel)
        {
            this.context.Projects.Remove(projectModel);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Views/Project/Create.cshtml
@model ProjectRider.Models.Project

@{
    ViewBag.Title = "Create";
}

<div class="wrapper">
    @using (Html.BeginForm("Create", "Project", FormMethod.Post, new { @class = "project-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Create New Project
        </div>
        <div class="create-title">
            <div class="create-title-label">Title</div>
            <input class="create-title-content" name="title" />
        </div>
        <div class="create-description">
            <div class="create-description-label">Description</div>
            <textarea rows="3" class="create-description-content" name="description"></textarea>
        </div>
        <div class="create-budget">
            <div class="create-budget-label">Budget</div>
            <input type="number" min="0" class="create-budget-content" name="budget" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Create Project</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Views/Project/Delete.cshtml
@model ProjectRider.Models.Project

@{
    ViewBag.Title = "Delete";
}

<div class="wrapper">
    @using (Html.BeginForm("Delete", "Project", FormMethod.Post, new { @class = "project-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Delete Project
        </div>
        <div class="create-title">
            <div class="create-title-label">Title</div>
            <input class="create-title-content" name="title" value="@Model.Title" disabled="disabled" />
        </div>
        <div class="create-description">
            <div class="create-description-label">Description</div>
            <textarea rows="3" class="create-description-content" name="description" disabled="disabled">@Model.Description</textarea>
        </div>
        <div class="create-budget">
            <div class="create-budget-label">Budget</div>
            <input type="number" min="0" class="create-budget-content" name="budget" value="@Model.Budget" disabled="disabled" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Delete Project</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Views/Project/Details.cshtml
@model ProjectRider.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Budget)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Views/Project/Edit.cshtml
@model ProjectRider.Models.Project

@{
    ViewBag.Title = "Edit";
}

<div class="wrapper">
    @using (Html.BeginForm("Edit", "Project", FormMethod.Post, new { @class = "project-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Edit Project
        </div>
        <div class="create-title">
            <div class="create-title-label">Title</div>
            <input class="create-title-content" name="title" value="@Model.Title" />
        </div>
        <div class="create-description">
            <div class="create-description-label">Description</div>
            <textarea rows="3" class="create-description-content" name="description">@Model.Description</textarea>
        </div>
        <div class="create-budget">
            <div class="create-budget-label">Budget</div>
            <input type="number" min="0" class="create-budget-content" name="budget" value="@Model.Budget" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Edit Project</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Views/Project/Index.cshtml
@model List<ProjectRider.Models.Project>

@{
    ViewBag.Title = "Index";
}
<div class="wrapper">
    <div class="button-holder">
        <a type="button" href="/create" class="log-button">Create New Project</a>
    </div>
    <div class="content">
        <div class="header">
            <div class="project-label">Project</div>
            <div class="budget-label">Budget</div>
            <div class="actions-label">Actions</div>
        </div>
        <div class="main">
            @foreach (var project in Model.ToList())
            {
                <div class="project">
                    <div class="project-title">
                        @(project.Title)
                    </div>
                    <div class="project-budget">
                        @(project.Budget)
                    </div>
                    <div class="project-actions">
                        @Html.ActionLink("Edit", "Edit", "Project", new { id = project.Id }, new { @class = "edit-button" })
                        @Html.ActionLink("Delete", "Delete", "Project", new { id = project.Id }, new { @class = "delete-button" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Software Technologies/07-ExamPreparations/ProjectRider/C#/ProjectRider/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>ProjectRider</title>
    <link rel="stylesheet" href="~/css/reset.css" type="text/css" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/create-style.css" type="text/css" />
</head>
<body>
    @RenderBody()
</body>
</html>