Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Models/Issue.cs
namespace IssueTracker.Models
{
    using System.ComponentModel.DataAnnotations;

    public class Issue
    {
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }
        [Required]
        public int Priority { get; set; }
    }
}

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Models/IssueDbContext.cs
namespace IssueTracker.Models
{
    using Microsoft.EntityFrameworkCore;

    public class IssueDbContext : DbContext
    {
        public DbSet<Issue> Issues { get; set; }

        public IssueDbContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySQL("server=localhost;database=issuetracker_asp;user=root;");
        }
    }
}

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Controllers/IssueController.cs
namespace IssueTracker.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using IssueTracker.Models;
    using System.Linq;
    using System.Collections.Generic;

    public class IssueController : Controller
    {
        private readonly IssueDbContext context;

        public IssueController(IssueDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            List<Issue> issues =
                this.context.Issues
               .ToList();

            return View(issues);
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
        {
            return View();

        }

        [HttpPost]
        [Route("create")]
        public ActionResult Create(Issue issue)
        {
            this.context.Issues.Add(issue);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult Edit(int id)
        {
            Issue issue = this.context.Issues.Find(id);
            return View(issue);
        }

        [HttpPost]
        [Route("edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirm(int id, Issue issueModel)
        {
            this.context.Issues.Update(issueModel);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("delete/{id}")]
        public ActionResult Delete(int id)
        {
            Issue issue = this.context.Issues.Find(id);
            return View(issue);
        }

        [HttpPost]
        [Route("delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int id, Issue issueModel)
        {
            this.context.Issues.Remove(issueModel);
            this.context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Views/Issue/Create.cshtml
@model IssueTracker.Models.Issue

@{
    ViewBag.Title = "Create";
}

<div class="wrapper">
    @using (Html.BeginForm("Create", "Issue", FormMethod.Post, new { @class = "issue-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Log Issue
        </div>
        <div class="create-title">
            <div class="create-title-label">Title</div>
            <input class="create-title-content" name="title" />
        </div>
        <div class="create-issueitem">
            <div class="create-issueitem-label">Content</div>
            <textarea rows="3" class="create-issueitem-content" name="content"></textarea>
        </div>
        <div class="create-issueitem">
            <div class="create-issueitem-label">Priority</div>
            <input type="number" min="0"  rows="3" class="create-issueitem-content" name="priority"/>
        </div>
        <div class="create-button-holder">
            <button type="submit" class="button">Log Issue</button>
            <a type="button" href="/" class="button">Back</a>
        </div>
    }
</div>

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Views/Issue/Delete.cshtml
@model IssueTracker.Models.Issue

@{
    ViewBag.Title = "Delete";
}

<div class="wrapper">
    @using (Html.BeginForm("Delete", "Issue", FormMethod.Post, new { @class = "issue-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Close Issue
        </div>
        <div class="create-title">
            <div class="create-title-label">Title</div>
            <input class="create-title-content" name="title" value="@Model.Title" disabled="disabled" />
        </div>
        <div class="create-issueitem">
            <div class="create-issueitem-label">Content</div>
            <textarea rows="3" class="create-issueitem-content" name="content" disabled="disabled">@Model.Content</textarea>
        </div>
        <div class="create-issueitem">
            <div class="create-issueitem-label">Priority</div>
            <input type="number" min="0"  rows="3" class="create-issueitem-content" name="priority" value="@Model.Priority" disabled="disabled"/>
        </div>
        <div class="create-button-holder">
            <button type="submit" class="button">Close Issue</button>
            <a type="button" href="/" class="button">Back</a>
        </div>
    }
</div>

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Views/Issue/Edit.cshtml
@model IssueTracker.Models.Issue

@{
    ViewBag.Title = "Edit";
}

<div class="wrapper">
    @using (Html.BeginForm("Edit", "Issue", FormMethod.Post, new { @class = "issue-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Edit Issue
        </div>
        <div class="create-title">
            <div class="create-title-label">Title</div>
            <input class="create-title-content" name="title" value="@Model.Title" />
        </div>
        <div class="create-issueitem">
            <div class="create-issueitem-label">Content</div>
            <textarea rows="3" class="create-issueitem-content" name="content">@Model.Content</textarea>
        </div>
        <div class="create-issueitem">
            <div class="create-issueitem-label">Priority</div>
            <input type="number" min="0"  rows="3" class="create-issueitem-content" value="@Model.Priority" name="priority"/>
        </div>
        <div class="create-button-holder">
            <button type="submit" class="button">Edit Issue</button>
            <a type="button" href="/" class="button">Back</a>
        </div>
    }
</div>

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Views/Issue/Index.cshtml
@model List<IssueTracker.Models.Issue>

@{
    ViewBag.Title = "Index";
}
<div class="wrapper">
    <div class="button-holder">
        <a type="button" href="/create" class="button">Log A New Issue</a>
    </div>
    <div class="content">
        <div class="header">
            <div class="issue-label">Issue</div>
            <div class="issue-label">Content</div>
            <div class="issue-label">Priority</div>
            <div class="actions-label">Actions</div>
        </div>
        <div class="main">
            @foreach (var issue in Model.ToList())
            {
            <div class="issue">
                <div class="issue-title">
                    @(issue.Title)
                </div>
                <div class="issue-item">
                    @(issue.Content)
                </div>
                <div class="issue-item">
                    @(issue.Priority)
                </div>
                <div class="project-actions">
                    @Html.ActionLink("Edit", "Edit", "Issue", new { id = issue.Id }, new { @class = "issuebutton" })
                    @Html.ActionLink("Close", "Delete", "Issue", new { id = issue.Id }, new { @class = "issuebutton" })
                </div>
            </div>
            }
        </div>
    </div>
</div>

Software Technologies/08-Exam-IssueTracker/C#/IssueTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Issue Tracker</title>
    <link rel="stylesheet" href="~/css/reset.css" type="text/css" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/create-style.css" type="text/css" />
</head>
<body style="background-color: lightblue">
    @RenderBody()
</body>
</html>