Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Models/Baby.cs
namespace SoftUniBabies.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public class Baby
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }
        
        [Required]
        public string Gender { get; set; }

        public string Birthday { get; set; }
    }
}

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Models/BabyDbContext.cs
namespace SoftUniBabies.Models
{
    using Microsoft.EntityFrameworkCore;

    public class BabyDbContext : DbContext
    {
        public DbSet<Baby> Babies { get; set; }

        public BabyDbContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySQL("server=localhost;database=softunibabies_csharp;user=root;");
        }
    }
}

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Controllers/BabyController.cs
namespace SoftUniBabies.Controllers
{
    using Models;
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Linq;

    public class BabyController : Controller
    {
        private readonly BabyDbContext dbContext;

        public BabyController(BabyDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            List<Baby> babies = this.dbContext.Babies.ToList();
            return View(babies);
        }

        [HttpGet]
        [Route("/create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Route("/create")]
        public IActionResult Create(Baby baby)
        {
            this.dbContext.Babies.Add(baby);
            this.dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("/edit/{id}")]
        public IActionResult Edit(int id)
        {
            Baby baby = this.dbContext
                .Babies
                .Find(id);

            return View(baby);
        }

        [HttpPost]
        [Route("/edit/{id}")]
        public IActionResult Edit(Baby baby)
        {
            this.dbContext.Babies.Update(baby);
            this.dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("/delete/{id}")]
        public IActionResult Delete(int id)
        {
            Baby baby = this.dbContext
                .Babies
                .Find(id);

            return View(baby);
        }

        [HttpPost]
        [Route("/delete/{id}")]
        public IActionResult Delete(Baby baby)
        {
            this.dbContext.Babies.Remove(baby);
            this.dbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Views/Baby/Create.cshtml
@model SoftUniBabies.Models.Baby

@{
    ViewBag.Title = "Create";
}

<div class="wrapper">
    @using (Html.BeginForm("Create", "Baby", FormMethod.Post, new { @class = "baby-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Register Baby
        </div>
        <div class="create-name">
            <div class="create-label">Name</div>
            <input class="create-content" name="name"/>
        </div>
        <div class="create-name">
            <div class="create-label">Gender</div>
            <select class="create-submit" name="gender">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
            </select>
        </div>
        <div class="create-name">
            <div class="create-label">Birth Day</div>
            <input type="date" min="2018-01-22" max="2018-04-27" class="create-content" name="birthday" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Add Baby</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Views/Baby/Delete.cshtml
@model SoftUniBabies.Models.Baby

@{
    ViewData["Title"] = "GrowUp";
}

<div class="wrapper">
    @using (Html.BeginForm("Delete", "Baby", FormMethod.Post, new { @class = "baby-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Grow Up
        </div>
        <div class="create-name">
            <div class="create-label">Name</div>
            <input class="create-content" name="name" value="@Model.Name" disabled="disabled" />
        </div>
        <div class="create-name">
            <div class="create-label">Gender</div>
            <input class="create-content" name="gender" disabled="disabled" value="@Model.Gender"/>
        </div>
        <div class="create-name">
            <div class="create-label">Birthday</div>
            <input type="date" min="2018-01-22" max="2018-04-27" class="create-content" name="birthday" value="@Model.Birthday" disabled="disabled" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Grow Up</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Views/Baby/Edit.cshtml
@model SoftUniBabies.Models.Baby

@{
    ViewBag.Title = "Edit";
}

<div class="wrapper">
    @using (Html.BeginForm("Edit", "Baby", FormMethod.Post, new { @class = "baby-create" }))
    {
        @Html.AntiForgeryToken()
        <div class="create-header">
            Edit Baby
        </div>
        <div class="create-name">
            <div class="create-label">Name</div>
            <input class="create-content" name="name" value="@Model.Name"/>
        </div>
        <div class="create-name">
            <div class="create-label">Gender</div>
            <select class="create-submit" name="gender" value="@Model.Gender">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
            </select>
        </div>
        <div class="create-name">
            <div class="create-label">Birth Day</div>
            <input type="date" min="2018-01-22" max="2018-04-27" class="create-content" name="birthday" value="@Model.Birthday" />
        </div>
        <div class="create-button-holder">
            <button type="submit" class="submit-button">Edit Baby</button>
            <a type="button" href="/" class="back-button">Back</a>
        </div>
    }
</div>

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Views/Baby/Index.cshtml
@model IEnumerable<SoftUniBabies.Models.Baby>

@{
    ViewData["Title"] = "SoftUni Babies";
}
<div class="wrapper">
    <div class="baby-create">
        <div class="create-header">
            SoftUni Babies
        </div>
    </div>
    <br />
    <div class="button-holder">
        <a type="button" href="/create" class="log-button">Register Baby</a>
    </div>
    <div class="content">
        <div class="header">
            <div class="baby-label">Name</div>
            <div class="baby-label">Gender</div>
            <div class="baby-label">Birthday</div>
            <div class="baby-label">Actions</div>
        </div>
        <div class="main">
            @foreach (var baby in Model.ToList())
            {
                <div class="baby">
                    <div class="baby-name">
                        @(baby.Name)
                    </div>
                    <div class="baby-name">
                        @(baby.Gender)
                    </div>
                    <div class="baby-name">
                        @(baby.Birthday)
                    </div>
                    <div class="baby-actions">
                        @Html.ActionLink("Edit", "Edit", "Baby", new { id = baby.Id }, new { @class = "edit-button" })
                        @Html.ActionLink("GrowUp", "Delete", "Baby", new { id = baby.Id }, new { @class = "delete-button" })
                    </div>
                </div>
            }
        </div>
    </div>
</div>

Software Technologies/07-ExamPreparations/Babies/CSharp/SoftUniBabies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>SoftUni Babies</title>
    <link rel="stylesheet" href="~/css/reset.css" type="text/css" />
    <link rel="stylesheet" href="~/css/style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/baby-style.css" type="text/css" />
</head>
<body>
    @RenderBody()
</body>
</html>