Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Models/Film.cs
namespace IMDB.Models
{
    using System.ComponentModel.DataAnnotations;

    public class Film
    {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }

        public string Genre { get; set; }

        public string Director { get; set; }

        public int Year { get; set; }




    }
}

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Models/IMDBDbContext.cs
namespace IMDB.Models
{
    using Microsoft.EntityFrameworkCore;

    public class IMDBDbContext : DbContext
    {
        public DbSet<Film> Films { get; set; }

        public IMDBDbContext()
        {
            this.Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseMySQL("server=localhost;database=imdb_asp;user=root;");
        }
    }
}

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Controllers/FilmController.cs
namespace IMDB.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Collections.Generic;
    using System.Linq;
    using Models;

    public class FilmController : Controller
    {
        private readonly IMDBDbContext dbContext;

        public FilmController(IMDBDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            var films = dbContext.Films.ToList();
            return View(films);
        }

        [HttpGet]
        [Route("/create")]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [Route("/create")]
        public IActionResult Create(Film film)
        {
            dbContext.Films.Add(film);
            dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Route("/edit/{id}")]
        public IActionResult Edit(int? id)
        {
            Film film = dbContext.Films.FirstOrDefault(f => f.Id == id);
            return View(film);
        }

        [HttpPost]
        [Route("/edit/{id}")]
        public IActionResult Edit(Film film)
        {
            dbContext.Update(film);
            dbContext.SaveChanges();
            return Redirect("/");
        }

        [HttpGet]
        [Route("/delete/{id}")]
        public IActionResult Delete(int? id)
        {
            Film film = dbContext.Films.Find(id);
            return View(film);
        }

        [HttpPost]
        [Route("/delete/{id}")]
        public IActionResult Delete(Film film)
        {
            dbContext.Remove(film);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Views/Film/Create.cshtml
@model IMDB.Models.Film

@{
    ViewBag.Title = "Create Film";
}

<h1>Create Film</h1>

<section>
    <div>

        @using (Html.BeginForm("Create", "Film", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="name">Name</label>
            <input type="text" id="name" name="name">
            <label for="genre">Genre</label>
            <input type="text" id="genre" name="genre">
            <label for="director">Director</label>
            <input type="text" id="director" name="director">
            <label for="year">Year</label>
            <input type="text" id="year" name="year">

            <button type="submit" class="">Create</button>
            <button onclick="location.href='/';return false;" class="cancel">Cancel</button>
        }

    </div>
</section>

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Views/Film/Delete.cshtml
@model IMDB.Models.Film

@{
    ViewBag.Title = "Delete Film";
}

<h1>Delete Film</h1>

<section>
    <div>

        @using (Html.BeginForm("Delete", "Film", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="name">Name</label>
            <input type="text" id="name" value="@Model.Name" disabled>
            <label for="genre">Genre</label>
            <input type="text" id="genre" value="@Model.Genre" disabled>
            <label for="director">Director</label>
            <input type="text" id="director" value="@Model.Director" disabled>
            <label for="year">Year</label>
            <input type="text" id="year" value="@Model.Year" disabled>

            <button type="submit" class="accept">Delete</button>
            <button onclick="location.href='/';return false;" class="cancel">Cancel</button>
        }

    </div>
</section>

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Views/Film/Edit.cshtml
@model IMDB.Models.Film

@{
    ViewBag.Title = "Edit Film";
}

<h1>Edit Film</h1>

<section>
    <div>

        @using (Html.BeginForm("Edit", "Film", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="name">Name</label>
            <input type="text" id="name" value="@Model.Name" name="name">
            <label for="genre">Genre</label>
            <input type="text" id="genre" value="@Model.Genre" name="genre">
            <label for="director">Director</label>
            <input type="text" id="director" value="@Model.Director" name="director">
            <label for="year">Year</label>
            <input type="text" id="year" value="@Model.Year" name="year">
            <button type="submit" class="accept">Edit</button>
            <button onclick="location.href='/';return false;" class="cancel">Cancel</button>
        }

    </div>
</section>

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Views/Film/Index.cshtml
@model List<IMDB.Models.Film>

@{
    ViewBag.Title = "All Films";
}

<h1>All Films</h1>

<div>
    <button onclick="location.href='/create';return false;" class="add-new">Create New Film</button>
</div>

<section>
    <div>
        <table>
            <tr>
                <th>Name</th>
                <th>Genre</th>
                <th>Director</th>
                <th>Year</th>
                <th>Actions</th>
            </tr>
            @foreach (var film in Model.ToList())
            {
                <tr>
                    <td>@film.Name</td>
                    <td>@film.Genre</td>
                    <td>@film.Director</td>
                    <td>@film.Year</td>
                    <td>
                        <button onclick="location.href='/edit/@film.Id';return false;" class="edit">Edit</button>
                        <button onclick="location.href='/delete/@film.Id';return false;" class="delete">Delete</button>
                    </td>
                </tr>
            }
        </table>
    </div>
</section>

Software Technologies/07-ExamPreparations/IMDB/C# Skeleton/IMDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>IMDB</title>
    <link href="~/css/style.css" rel="stylesheet" />
</head>
<body>
	@RenderBody()
</body>
</html>